### PR TITLE
Fix XSS vulnerability

### PR DESCRIPTION
**Pull request by paulyi**
**Description**
Any HTML contained in `msg` will be rendered in the dom. This creates an XSS vulnerability if `msg` could be user input. 

**Solution**
Insert `msg` as text. This will just display the string as is without trying to render any possible HTML contained within it.

### CODE REVIEW

**Comment by j1mmie** [comment]
@SLMNBJ Our team here discovered an XSS vulnerability in this repo. Any chance you are free to review this PR, merge, and re-release to NPM? If not, not biggie, we can fork the project. Let us know if we can help in any way

**Comment by paulyi** [comment]
@SLMNBJ Just bumping one more time before we fork. Let us know if there's anything we can do to help.

**Comment by paulyi** [comment]
@SLMNBJ Thank you for merging this in! If it's not too much trouble, could we get a new version published to NPM as well? 

Let us know if there's anything you need from us.

**Comment by SalmenBejaoui** [comment]
Hi @paulyi,

I published the new version on npm.

Thanks for the PR.

**Pull request merged**
